### PR TITLE
Modified the gen_htaccess script to use text/plain rather than text/html

### PR DESCRIPTION
**Pull request by Wol**
Can then use `php couch/gen_htaccess.php > .htaccess` on the server to update the htaccess file without having to load it in a separate web browser and copy/paste into a text editor.

There is then a check to see if the script is being run on the server itself, and if so, it disables the check to see if the user is logged into the web admin panel.

### CODE REVIEW

**Comment by cheesypoof** [comment]
The new admin panel currently being worked on displays the htaccess code in a modal window (iframe). For that reason, we display the contents in HTML. The inclusion of that change to HTML in 1.4.5RC1 was perhaps premature though as the new admin panel didn't make it into that update.

I believe at best, generating the htaccess file with a cli would offer very minimal benefit for those few that are comfortable with such a workflow. I also can't help but think that whenever someone would need to create/update their htaccess file, they would already be logged into the admin panel. This is especially the case if one follows the recommended approach to only enable pretty urls once development has completed. Additionally, it is very common for there to be other unrelated (non-Couch) code in an htaccess file.

I am going to close this for now as cli usage also isn't quite on our radar. I'm sorry we couldn't merge this @Wol; if you are preparing a large change or are unsure about a potential pull request, feel free to run it by us on the forums. Thanks and we do appreciate your efforts.

**Comment by Wol** [comment]
It was more that the first time I tried saving it from my web browser just using Ctrl+S, because Couch had told my browser that it was a HTML document, the page was saved with all the HTML markup in. Currently you have to rely on the browser/text editor to do the HTML > text/plain translation when using copy/paste.

If Couch told the browser that it's a text/plain document, then it would give the user the option to save the file to disk in the correct format using the standard "Save Page As" / Ctrl+S option. They can then load up in a text editor to edit further or FTP it to the server directly.

I agree with your point regarding the use of CLI in the workflow though and can see where you're coming from on that. Had overlooked the point regarding when pretty urls are enabled!

**Comment by cheesypoof** [comment]
Every browser I tested handled the copy/paste properly.

I hadn't considered the scenario where someone would save the page directly... That case is sufficient to warrant reverting to text/plain and removing the HTML. Thanks for the insight!

**Comment by Wol** [comment]
Yeah the copy paste works absolutely fine as there isn't any strange markup / styling that would break the text handling. It was just the Ctrl+S case which saved the HTML styling.

**Pull request closed without merging**
