### PR TITLE
Create HI.php

### PR DESCRIPTION
**Pull request by genxcoders**
Please let me know if this is of any help

### CODE REVIEW

**Comment by cheesypoof** [comment]
I am not sure what the criteria is, for a language to be added to core, as opposed to the https://github.com/CouchCMS/Translations repository. Perhaps @kksidd can provide some details...

**Comment by kksidd** [comment]
@cheesypoof , I'll ask @genxcoders to submit the commit to the https://github.com/CouchCMS/Translations repository as that would be the right place for it.

**Comment by genxcoders** [comment]
@kksidd sir and @cheesypoof I have made the changes as were suggested by the two of you. Hope it will be helpful.

I dont quite know how GitHub Works, as I am new at using it. I hope the submission that I have made shows up on the https://github.com/CouchCMS/Translations repository.

**Comment by cheesypoof** [comment]
You pushed the changes to your fork @genxcoders. Could you also create a new pull request for the other repository?

**Comment by genxcoders** [comment]
@cheesypoof actually i am new to GitHub... Could you in short direct me to what you want me to do... Please...

**Comment by cheesypoof** [comment]
You created a pull request for the main CouchCMS repository without issue. I am not requesting you do something too different; this time target the Translations repository.

https://help.github.com/articles/using-pull-requests/

**Comment by genxcoders** [comment]
@cheesypoof i created a pull request... i hope it is the correct thing done...

**Pull request closed without merging**
