### PR TITLE
Update too long german translations

### PR DESCRIPTION
**Pull request by SimonWpt**
I changed two translations, which break the boundaries of the buttons:

view_site = Vorschau (means preview)
browse_server = Dateiliste (means filelist)

### CODE REVIEW

**Comment by kksidd** [comment]
Thanks Simon.

The 'File List' for 'Browse Server' seems ok. However, the 'Preview' for 'View Site' really conveys something else - the original sense is that the button just leads to the frontend.

Your thoughts?

**Comment by SimonWpt** [comment]
The old translation for `view_site` is __Seite ansehen__ which means literally __view page__ not __view site__.

Possible short translations would be:
__Website__ (*website*)
__Ansehen__ (*view*)
__Zeige Site__ (*show site*)

Do you have a favorite?

**Comment by kksidd** [comment]
Zeige Site (show site) seems just fine - is it short enough not to break the button boundary? If yes, please use it; else please use plain 'Website'. Thanks.

**Comment by SimonWpt** [comment]
**Zeige Site** fits perfect. :)
image

**Comment by SimonWpt** [comment]
Thank you.

**Pull request merged**
